### ISSUE TITLE
Cannot start the tapo bridge app due to error `KeyError: 'result'`

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/matter-bridge-tapo#10]
commands:
```
sudo snap install matter-bridge-tapo-lighting --edge
sudo snap set matter-bridge-tapo-lighting ip="192.168.178.61"
sudo snap set matter-bridge-tapo-lighting user="xxxxxx@gmail.com"
sudo snap set matter-bridge-tapo-lighting password="dhdmLy_zKf.aKKxxxxx2"
sudo snap connect matter-bridge-tapo-lighting:avahi-control
sudo snap start matter-bridge-tapo-lighting
```

error logs:
```
$ snap logs -f matter-bridge-tapo-lighting.tapo-bridge
2023-11-07T09:25:41+01:00 systemd[1]: Started snap.matter-bridge-tapo-lighting.tapo-bridge.service - Service for snap application matter-bridge-tapo-lighting.tapo-bridge.
2023-11-07T09:25:41+01:00 matter-bridge-tapo-lighting.tapo-bridge[20303]: venv: /snap/matter-bridge-tapo-lighting/5/connectedhomeip/python_env
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]: Starting Tapo Bridge Lighting App
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]: beilimengmeng@gmail.com dhdmLy_zKf.aKKH7T8p2
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]: [tapo] 192.168.178.61: handshake
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]: Traceback (most recent call last):
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]:   File "/snap/matter-bridge-tapo-lighting/5/bin/lighting.py", line 170, in <module>
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]:     dev.handshake()
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]:   File "/snap/matter-bridge-tapo-lighting/5/connectedhomeip/python_env/lib/python3.10/site-packages/PyP100/PyP100.py", line 129, in handshake
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]:     encryptedKey = r.json()["result"]["key"]
2023-11-07T09:25:42+01:00 matter-bridge-tapo-lighting.tapo-bridge[20350]: KeyError: 'result'
2023-11-07T09:25:42+01:00 systemd[1]: snap.matter-bridge-tapo-lighting.tapo-bridge.service: Main process exited, code=exited, status=1/FAILURE
2023-11-07T09:25:42+01:00 systemd[1]: snap.matter-bridge-tapo-lighting.tapo-bridge.service: Failed with result 'exit-code'.
2023-11-07T09:25:52+01:00 systemd[1]: snap.matter-bridge-tapo-lighting.tapo-bridge.service: Scheduled restart job, restart counter is at 125.
2023-11-07T09:25:52+01:00 systemd[1]: Stopped snap.matter-bridge-tapo-lighting.tapo-bridge.service - Service for snap application matter-bridge-tapo-lighting.tapo-bridge.
2023-11-07T09:25:52+01:00 systemd[1]: Started snap.matter-bridge-tapo-lighting.tapo-bridge.service - Service for snap application matter-bridge-tapo-lighting.tapo-bridge.
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20353]: venv: /snap/matter-bridge-tapo-lighting/5/connectedhomeip/python_env
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]: Starting Tapo Bridge Lighting App
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]: xxxxxxxxx@gmail.com dhdmLy_zKf.aKKxxxxp2
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]: [tapo] 192.168.178.61: handshake
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]: Traceback (most recent call last):
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]:   File "/snap/matter-bridge-tapo-lighting/5/bin/lighting.py", line 170, in <module>
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]:     dev.handshake()
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]:   File "/snap/matter-bridge-tapo-lighting/5/connectedhomeip/python_env/lib/python3.10/site-packages/PyP100/PyP100.py", line 129, in handshake
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]:     encryptedKey = r.json()["result"]["key"]
2023-11-07T09:25:52+01:00 matter-bridge-tapo-lighting.tapo-bridge[20394]: KeyError: 'result'
2023-11-07T09:25:52+01:00 systemd[1]: snap.matter-bridge-tapo-lighting.tapo-bridge.service: Main process exited, code=exited, status=1/FAILURE
2023-11-07T09:25:52+01:00 systemd[1]: snap.matter-bridge-tapo-lighting.tapo-bridge.service: Failed with result 'exit-code'.
```

**Comment by farshidtz** [comment]
As logs show, the KeyError is from the PyP100 library raised during handshaking. The library doesn't print the content of the object, when 'result' is missing.
